version: '3.4'
services:
  graphql:
    build:
      context: ./graphql
      dockerfile: Dockerfile
    volumes:
      - ./graphql:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=mysql-db
      - DB_USER=root
      - DB_PASS=password
      - DB_COLLATION=utf8mb4_unicode_ci
    ports:
      - "80:80"
    tty: true
  db:
    image: mysql:5.7
    ports:
    - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./mysql/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql-db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 1234:80