version: '3.4'
services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      TZ: Asia/Tokyo
    ports:
      - "8080:8080"
    tty: true
